// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA1jiiCYhu6ybDpDc1afooRK0xLHXoZPw',
    appId: '1:920534460259:web:b2357b9b7c5aad43681556',
    messagingSenderId: '920534460259',
    projectId: 'flutter-login-57251',
    authDomain: 'flutter-login-57251.firebaseapp.com',
    storageBucket: 'flutter-login-57251.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALnD9NPRidzCJMq9rORNPif2B2Crx4Lmw',
    appId: '1:920534460259:android:3fb41e663bc35523681556',
    messagingSenderId: '920534460259',
    projectId: 'flutter-login-57251',
    storageBucket: 'flutter-login-57251.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcKY1QlNhP-7KuW3Mgec1sSD0ZFcTwlMw',
    appId: '1:920534460259:ios:d3e9b5857891167f681556',
    messagingSenderId: '920534460259',
    projectId: 'flutter-login-57251',
    storageBucket: 'flutter-login-57251.appspot.com',
    iosBundleId: 'com.example.spotted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcKY1QlNhP-7KuW3Mgec1sSD0ZFcTwlMw',
    appId: '1:920534460259:ios:d3e9b5857891167f681556',
    messagingSenderId: '920534460259',
    projectId: 'flutter-login-57251',
    storageBucket: 'flutter-login-57251.appspot.com',
    iosBundleId: 'com.example.spotted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA1jiiCYhu6ybDpDc1afooRK0xLHXoZPw',
    appId: '1:920534460259:web:0106c7fe72a6d1ee681556',
    messagingSenderId: '920534460259',
    projectId: 'flutter-login-57251',
    authDomain: 'flutter-login-57251.firebaseapp.com',
    storageBucket: 'flutter-login-57251.appspot.com',
  );
}
